# Generated by Django 5.2 on 2025-04-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NR', 'Nombre Regional'), ('NUIP', 'NUIP'), ('PAS', 'Pasaporte'), ('PEP', 'Permiso Especial de Permanencia'), ('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('TP', 'Tarjeta Prueba'), ('NIT', 'NIT')], max_length=10)),
                ('numero_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono_celular', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('digito_verificacion', models.CharField(max_length=5)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('tipo_empresa', models.CharField(choices=[('comercializador', 'Comercializador'), ('transformador', 'Transformador'), ('exportador', 'Exportador')], max_length=20)),
                ('naturaleza_empresa', models.CharField(choices=[('privada', 'Privada'), ('publica', 'Pública'), ('mixta', 'Mixta')], max_length=10)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_celular', models.CharField(max_length=15)),
                ('quien_diligencia', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('representante_legal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_representadas', to='personas.persona')),
            ],
        ),
    ]
